# Generated by Django 4.1.5 on 2023-01-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='')),
                ('cover_letter', models.FileField(upload_to='')),
                ('date_submitted', models.DateField()),
                ('status', models.CharField(default='In progress', max_length=255)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='main.applicant')),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='main.position')),
                ('reviewed_by_manager', models.ForeignKey(db_column='reviewed_by_manager_id', on_delete=django.db.models.deletion.CASCADE, to='main.manager')),
            ],
        ),
    ]
