# Generated by Django 4.1.5 on 2023-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(default=20230126),
        ),
    ]
