# Generated by Django 4.1.5 on 2023-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_applicant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
