# Generated by Django 4.1.5 on 2023-01-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_applicant_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewed_by_manager',
            field=models.ForeignKey(db_column='reviewed_by_manager_id', default='Amil', on_delete=django.db.models.deletion.CASCADE, to='main.manager'),
        ),
    ]
