# Generated by Django 4.1.5 on 2023-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.ImageField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
