# Generated by Django 4.1.5 on 2023-01-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
