# Generated by Django 4.1.5 on 2023-01-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_applicant_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='main.applicant')),
            ],
        ),
    ]
