# Generated by Django 4.1.5 on 2023-01-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewed_by_manager',
            field=models.ForeignKey(db_column='reviewed_by_manager_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.manager'),
        ),
    ]
