# Generated by Django 4.1.5 on 2023-01-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_test_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(db_column='position_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
    ]
