# Generated by Django 4.1.5 on 2023-01-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_test_position_test_reviewed_by_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='resume',
            field=models.ImageField(default=None, upload_to='files/'),
        ),
    ]
