# Generated by Django 4.1.5 on 2023-01-29 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='main.applicant'),
        ),
        migrations.AlterField(
            model_name='test',
            name='position',
            field=models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
    ]
