# Generated by Django 4.1.5 on 2023-01-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_test_applicant_alter_test_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='main.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='main.position'),
        ),
    ]
