# Generated by Django 4.1.5 on 2023-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
